openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://swaggerhub.ct.blue.cdtapps.com/virts/Payments/CaptureService/1.0.0
info:
  description: Capture service API
  version: "1.0.0"
  title: Capture service API
paths:
  /{retailUnit}/{iopgId}/executeinstruction:
    post:
      summary: executes a capture/ reversal
      operationId: executeInstruction
      description: can execute a capture / reversal
      parameters:
        - in: path
          name: retailUnit
          description: retailUnit
          required: true
          schema:
            type: string
        - in: path
          name: iopgId
          description: IopgId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CapturePaymentInstructionEvent'
        description: PaymentInstruction
        required: true
      responses:
        '200':
          description: "ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentCaptureCompletedEvent'
components:
  schemas:
    PaymentInstruction:
      type: object
      required: 
        - type
        - reconciliationId
        - amount
        - currency
        - retailUnit
        - trackingId
        - authorisations
      properties:
        retailUnit:
          type: string
          description: country
          example: "SE"
        trackingIdentifiers:
          items:
            $ref: '#/components/schemas/TrackingIdentifiers'
          description: "Interal tracking ID that can be set by consuming system basically to be able to link the performed instruction against the event it generates"
        reconciliationId:
          type: string
          example: "32837283223"
          description: "Id used for reconcilliation, typically iSell order number"
        amount:
          type: number
          format: bigdecimal
          example: 45.6700000000000017053025658242404460906982421875
          description: "Payment amount for the transaction."
        currency:
          type: string
          example: "EUR"
          description: "Currency Code (ISO 4217) to be used for the transaction"
        taxDetails:
          items:
            $ref: '#/components/schemas/TaxDetails'
        authorisations:
          type: array
          description: "List of current autorisations on the order"
          items:
            $ref: "#/components/schemas/Authorisation"
        orderLines:
          type: array
          items:
            $ref: "#/components/schemas/OrderLine"
    OrderLine:
      type: object
      required: 
       - lineType
       - quantity
       - unitOfMeasure
       - amount
       - taxDetails
       - itemNo
       - itemType
      properties:
        lineType:
          type: string
          example: "goods"
          description: Type of order line
          enum:
            - goods
            - service
            - delivery
        quantity:
          type: number
          format: bigdecimal
          example: 2
        unitOfMeasure:
          type: string
          description: Unit of measure
          enum:
            - Pieces
            - Meter
            - Kg
            - CubicMeter
            - Each
        amount:
          type: number
          format: bigdecimal
          example: 50
          description: Total value of the line including discounts
        taxAmount:
          type: number
          format: bigdecimal
          example: 15.6699999999999999289457264239899814128875732421875
          description: total tax on the order item
        taxDetails:
          items:
            $ref: '#/components/schemas/TaxDetails'
        discountAmount:
          type: number
          format: bigdecimal
          example: 10
          description: total discount
        itemNo:
          type: string
          example: "002.110.88"
        itemType:
          type: string
          example: "ART"
          enum:
          - "ART"
          - "SPR"
          - "SGR"
        itemName:
          type: string
          example: "Billy"
        itemDesc:
          type: string
          example: "Bookcase"
        itemUnitPrice:
          type: number
          format: bigdecimal
          example: 25
          description: "Original unit price of the item"
        itemUnitTax:
          type: number
          format: "bigdecimal"
          example: 5
          description: "Unit price tax"
    Authorisation:
      type: object
      properties:
        paymentGatewayReference:
          $ref: '#/components/schemas/PaymentGatewayReference'
        amount:
          type: number
          format: bigdecimal
          example: 50
          description: authorized amount
        paymentBrand:
          type: string
          example: "KLARNAPAYLATER"
        expiryDate:
          type: string
          description: expiry date for the authorisation if present
          example: "2021-05-11 07:04:43+0000"
    CapturePaymentInstructionEvent:
      allOf:
        - $ref: '#/components/schemas/PaymentInstruction'
        - type: object
          properties:
            type: 
              enum: [CapturePaymentInstructionEvent]
              type: string
    ReversePaymentInstructionEvent:
      allOf:
        - $ref: '#/components/schemas/PaymentInstruction'
        - type: object
          properties:
            type: 
              enum: [ReversePaymentInstructionEvent]
              type: string
    PaymentCaptureCompletedEvent:
      allOf:
      - $ref: '#/components/schemas/PaymentTransaction'
      - type: object
        properties:
          type: 
            enum: [PaymentCaptureCompletedEvent]
            type: string
    PaymentCaptureFailedEvent:
      allOf:
      - $ref: '#/components/schemas/PaymentTransaction'
      - type: object
        properties:
          type: 
            enum: [PaymentCaptureFailedEvent]
            type: string
    PaymentReverseCompletedEvent:
      allOf:
      - $ref: '#/components/schemas/PaymentTransaction'
      - type: object
        properties:
          type: 
            enum: [PaymentReverseCompletedEvent]
            type: string
    PaymentReverseFailedEvent:
      allOf:
      - $ref: '#/components/schemas/PaymentTransaction'
      - type: object
        properties:
          type: 
            enum: [PaymentReverseFailedEvent]
            type: string
    PaymentTransaction:
      type: object   
      discriminator:
        propertyName: className
      required:
        - className
        - amount
        - currency
        - paymentGatewayReference
        - parentPaymentGatewayReference
        - trackingIdentifiers
      properties:
        className: 
          type: string
        amount:
          type: number
          format: bigdecimal
          example: 999.99
        currency:
          type: string
          example: "SEK"
        paymentGatewayReference:
           $ref: '#/components/schemas/PaymentGatewayReference'
        parentPaymentGatewayReference:
           $ref: '#/components/schemas/PaymentGatewayReference'
        reconciliationId:
          type: string
          example: "32837283223"
          description: "Id used for reconcilliation, typically iSell order number"
        trackingIdentifiers:
          items:
            $ref: '#/components/schemas/TrackingIdentifiers'
          description: "Corresponding trackingId from the PaymentInstruction. Note that an instruction could lead to multiple captures/reversals depending on amount"
    PaymentGatewayReference:
      type: object
      properties:
        paymentGatewayReferenceId:
          type: string
          description: reference id of the transaction
          example: "9d7f3a75-c4d5-444f-85e8-43f7630e0d71"
        paymentGateway:
          type: string
          enum: [IOPG]
    TaxDetails:
      type: object
      required:
       - taxType
       - taxPercentage
       - taxAmount
       - taxCode
      properties:
        taxType: 
          type: string
          example: VAT
          description: Type of tax
        taxCode:
          type: string
          example: "405"
          description: tax code
        taxJurisdiction:
          type: object
          properties:
            type:
              type: string
              example: "DISTRICT"
              description: tax jurisdiction type
            code:
              type: string
              example: "2398"
              description: tax jurisdiction code            
        taxPercentage: 
          type: number
          example: 20
          description: Tax percentage for the given tax type
        taxableAmount:
          type: number
          example: 100
          description: taxable amount
        taxAmount:
          type: number
          description: Tax amount
    TrackingIdentifiers:
      type: object
      properties:
        id:
          type: string
          example: "12234343545"
        type:
          type: string
          example: "WORKORDER_ID"